version: '3'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/src
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload